- name: My first play
  hosts: myhosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

   - name: Update and upgrade apt packages
     become: true
     apt:
       upgrade: yes
       update_cache: yes

   - name: Reboot the server if a reboot is required
     become: true
     ansible.builtin.reboot:
       connect_timeout: 30
       reboot_timeout: 30
       post_reboot_delay: 30
       test_command: uptime

#   - name: Update apt Packages
#     ansible.builtin.apt:
#      update_cache: True
#      upgrade: dist
#      autoremove: True
#     become: true
